# Generated by Django 6.0.1 on 2026-01-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='current_status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived at Destination')], default='BOOKED', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipmenthistory',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived at Destination')], max_length=20),
        ),
    ]
