# Generated by Django 6.0.1 on 2026-01-29 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_add_bus_to_shipment'),
        ('shipment', '0002_alter_shipment_current_status_and_more'),
    ]

    operations = [
    ]
