# Generated by Django 6.0.1 on 2026-01-31 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_add_day_to_shipment'),
        ('shipment', '0003_merge_20260129_1951'),
    ]

    operations = [
    ]
