# Generated by Django 6.0.1 on 2026-01-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_organization_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='password',
        ),
    ]
