# Generated by Django 6.0.1 on 2026-01-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_branch_owner_organization_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='password',
        ),
    ]
