# Generated by Django 6.0.1 on 2026-01-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_branch_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'permissions': [('is_branch_admin', 'Is Branch Admin')]},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('is_organization_admin', 'Is Organization Admin')]},
        ),
    ]
