# Generated by Django 6.0.1 on 2026-01-31 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_create_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='current_operational_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='branch',
            name='last_day_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
